import { FIXED_COLORS } from "../../theme/colors";

export interface CalendarEvent {
  id: string;
  title: string;
  time: string;
  type: "workout" | "measurement" | "goal" | "reminder";
  description?: string;
  color: string;
}

export const calendarMockData: Record<string, CalendarEvent[]> = {
  // Outubro 2025
  "2025-10-01": [
    {
      id: "1",
      title: "Treino de Peito",
      time: "09:00",
      type: "workout",
      description: "Supino, Flexão, Crucifixo",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "2",
      title: "Medição de Peso",
      time: "08:00",
      type: "measurement",
      description: "Peso: 75.5kg",
      color: FIXED_COLORS.success[500],
    },
    {
      id: "3",
      title: "Lembrete: Hidratação",
      time: "12:00",
      type: "reminder",
      description: "Beber 2L de água",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-02": [
    {
      id: "4",
      title: "Treino de Costas",
      time: "18:00",
      type: "workout",
      description: "Puxada, Remada, Prancha",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "5",
      title: "Medição de Cintura",
      time: "19:30",
      type: "measurement",
      description: "Cintura: 85cm",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-03": [
    {
      id: "6",
      title: "Treino de Pernas",
      time: "07:00",
      type: "workout",
      description: "Agachamento, Leg Press, Panturrilha",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "7",
      title: "Meta de Proteína",
      time: "14:00",
      type: "goal",
      description: "Consumir 150g de proteína",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-04": [
    {
      id: "8",
      title: "Treino de Ombros",
      time: "17:00",
      type: "workout",
      description: "Desenvolvimento, Elevação Lateral, Crucifixo",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "9",
      title: "Lembrete: Sono",
      time: "22:00",
      type: "reminder",
      description: "Dormir 8 horas",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-05": [
    {
      id: "10",
      title: "Treino de Braços",
      time: "16:00",
      type: "workout",
      description: "Rosca Bíceps, Tríceps, Antebraço",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "11",
      title: "Medição de Braço",
      time: "15:30",
      type: "measurement",
      description: "Braço: 35cm",
      color: FIXED_COLORS.success[500],
    },
    {
      id: "12",
      title: "Meta de Água",
      time: "10:00",
      type: "goal",
      description: "Beber 3L de água",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-06": [
    {
      id: "13",
      title: "Cardio",
      time: "08:00",
      type: "workout",
      description: "Corrida 30min, Bike 20min",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "14",
      title: "Lembrete: Alongamento",
      time: "19:00",
      type: "reminder",
      description: "Sessão de alongamento",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-07": [
    {
      id: "15",
      title: "Treino de Core",
      time: "18:30",
      type: "workout",
      description: "Prancha, Abdominal, Prancha Lateral",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "16",
      title: "Medição de Peso",
      time: "07:00",
      type: "measurement",
      description: "Peso: 75.2kg",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-08": [
    {
      id: "17",
      title: "Treino de Peito",
      time: "09:00",
      type: "workout",
      description: "Supino Inclinado, Flexão, Crucifixo Inclinado",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "18",
      title: "Meta de Carboidratos",
      time: "13:00",
      type: "goal",
      description: "Consumir 200g de carboidratos",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-09": [
    {
      id: "19",
      title: "Treino de Costas",
      time: "17:30",
      type: "workout",
      description: "Puxada Frontal, Remada Curvada, Puxada Atrás",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "20",
      title: "Lembrete: Suplementos",
      time: "20:00",
      type: "reminder",
      description: "Tomar whey protein",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-10": [
    {
      id: "21",
      title: "Treino de Pernas",
      time: "16:00",
      type: "workout",
      description: "Agachamento Livre, Stiff, Panturrilha em Pé",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "22",
      title: "Medição de Coxa",
      time: "15:30",
      type: "measurement",
      description: "Coxa: 58cm",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-11": [
    {
      id: "23",
      title: "Treino de Ombros",
      time: "18:00",
      type: "workout",
      description:
        "Desenvolvimento com Halteres, Elevação Frontal, Elevação Lateral",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "24",
      title: "Meta de Gordura",
      time: "12:00",
      type: "goal",
      description: "Consumir 60g de gordura",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-12": [
    {
      id: "25",
      title: "Treino de Braços",
      time: "17:00",
      type: "workout",
      description: "Rosca Direta, Tríceps Pulley, Rosca Martelo",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "26",
      title: "Lembrete: Descanso",
      time: "21:00",
      type: "reminder",
      description: "Descansar para recuperação",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-13": [
    {
      id: "27",
      title: "Cardio HIIT",
      time: "08:30",
      type: "workout",
      description: "HIIT 25min - Burpees, Mountain Climbers, Jumping Jacks",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "28",
      title: "Medição de Peso",
      time: "07:30",
      type: "measurement",
      description: "Peso: 75.0kg",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-14": [
    {
      id: "29",
      title: "Treino de Core",
      time: "19:00",
      type: "workout",
      description: "Prancha 3x1min, Abdominal 3x20, Prancha Lateral 3x30s",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "30",
      title: "Meta de Sono",
      time: "22:30",
      type: "goal",
      description: "Dormir 8 horas",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-15": [
    {
      id: "31",
      title: "Treino de Peito",
      time: "09:30",
      type: "workout",
      description: "Supino Declinado, Flexão Diamante, Crucifixo Declinado",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "32",
      title: "Lembrete: Hidratação",
      time: "11:00",
      type: "reminder",
      description: "Beber 500ml de água",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-16": [
    {
      id: "33",
      title: "Treino de Costas",
      time: "18:15",
      type: "workout",
      description: "Puxada Aberta, Remada Unilateral, Puxada Fechada",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "34",
      title: "Medição de Cintura",
      time: "19:45",
      type: "measurement",
      description: "Cintura: 84cm",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-17": [
    {
      id: "35",
      title: "Treino de Pernas",
      time: "16:30",
      type: "workout",
      description: "Agachamento Sumô, Leg Press 45°, Panturrilha Sentado",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "36",
      title: "Meta Mensal",
      time: "20:00",
      type: "goal",
      description: "Avaliar progresso do mês",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-18": [
    {
      id: "37",
      title: "Treino de Ombros",
      time: "17:45",
      type: "workout",
      description:
        "Desenvolvimento Arnold, Elevação Lateral, Elevação Posterior",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "38",
      title: "Lembrete: Suplementos",
      time: "21:15",
      type: "reminder",
      description: "Tomar creatina",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-19": [
    {
      id: "39",
      title: "Treino de Braços",
      time: "16:45",
      type: "workout",
      description: "Rosca 21, Tríceps Francês, Rosca Concentrada",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "40",
      title: "Medição de Braço",
      time: "16:15",
      type: "measurement",
      description: "Braço: 35.5cm",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-20": [
    {
      id: "41",
      title: "Cardio Steady State",
      time: "09:00",
      type: "workout",
      description: "Esteira 45min - Ritmo constante",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "42",
      title: "Meta de Água",
      time: "14:30",
      type: "goal",
      description: "Beber 3.5L de água",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-21": [
    {
      id: "43",
      title: "Treino de Core",
      time: "18:30",
      type: "workout",
      description: "Prancha 4x1min, Abdominal 4x25, Prancha Lateral 4x45s",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "44",
      title: "Lembrete: Alongamento",
      time: "19:45",
      type: "reminder",
      description: "Sessão de alongamento 15min",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-22": [
    {
      id: "45",
      title: "Treino de Peito",
      time: "08:45",
      type: "workout",
      description: "Supino Inclinado, Flexão Pike, Crucifixo Inclinado",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "46",
      title: "Medição de Peso",
      time: "08:15",
      type: "measurement",
      description: "Peso: 74.8kg",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-23": [
    {
      id: "47",
      title: "Treino de Costas",
      time: "17:15",
      type: "workout",
      description: "Puxada Supinada, Remada T, Puxada Alta",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "48",
      title: "Meta de Proteína",
      time: "13:30",
      type: "goal",
      description: "Consumir 160g de proteína",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-24": [
    {
      id: "49",
      title: "Treino de Pernas",
      time: "16:45",
      type: "workout",
      description: "Agachamento Búlgaro, Leg Press, Panturrilha no Leg Press",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "50",
      title: "Lembrete: Sono",
      time: "22:15",
      type: "reminder",
      description: "Dormir 8.5 horas",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-25": [
    {
      id: "51",
      title: "Treino de Ombros",
      time: "18:00",
      type: "workout",
      description:
        "Desenvolvimento Militar, Elevação Lateral, Elevação Frontal",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "52",
      title: "Medição de Ombros",
      time: "17:30",
      type: "measurement",
      description: "Ombros: 110cm",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-26": [
    {
      id: "53",
      title: "Treino de Braços",
      time: "17:30",
      type: "workout",
      description: "Rosca Alternada, Tríceps Testa, Rosca Inversa",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "54",
      title: "Meta de Carboidratos",
      time: "12:45",
      type: "goal",
      description: "Consumir 220g de carboidratos",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-27": [
    {
      id: "55",
      title: "Cardio Intervalado",
      time: "08:15",
      type: "workout",
      description: "Bike 30min - 2min alta/1min baixa intensidade",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "56",
      title: "Lembrete: Hidratação",
      time: "15:00",
      type: "reminder",
      description: "Beber 1L de água",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-28": [
    {
      id: "57",
      title: "Treino de Core",
      time: "19:00",
      type: "workout",
      description: "Prancha 4x1min, Abdominal 4x25, Prancha Lateral 4x45s",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "58",
      title: "Meta de Sono",
      time: "22:30",
      type: "goal",
      description: "Dormir 8.5 horas",
      color: FIXED_COLORS.warning[500],
    },
  ],
  "2025-10-29": [
    {
      id: "59",
      title: "Treino de Peito",
      time: "09:30",
      type: "workout",
      description: "Supino Declinado, Flexão Diamante, Crucifixo Declinado",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "60",
      title: "Lembrete: Hidratação",
      time: "11:00",
      type: "reminder",
      description: "Beber 500ml de água",
      color: FIXED_COLORS.primary[400],
    },
  ],
  "2025-10-30": [
    {
      id: "61",
      title: "Treino de Costas",
      time: "18:15",
      type: "workout",
      description: "Puxada Aberta, Remada Unilateral, Puxada Fechada",
      color: FIXED_COLORS.primary[500],
    },
    {
      id: "62",
      title: "Medição de Cintura",
      time: "19:45",
      type: "measurement",
      description: "Cintura: 83cm",
      color: FIXED_COLORS.success[500],
    },
  ],
  "2025-10-31": [],
};
