import { DietPlan } from "./types";

export const getMockDietPlan = (): DietPlan => ({
  name: "Minha Dieta Low Carb - Emagrecimento",
  description: "Dieta que estou seguindo para perder 5kg",
  is_active: true,
  meals: [
    {
      id: "breakfast-1",
      name: "Café da Manhã",
      description: "Café proteico sem carboidratos",
      meal_type: "breakfast",
      time: "08:00",
      calories: 350,
      protein: 30,
      carbs: 10,
      fat: 20,
      image: require("../../../../../assets/images/protein-types.jpeg"),
      ingredients: [
        {
          name: "Ovos Mexidos",
          quantity: 3,
          unit: "unidades",
          category: "Proteína",
          calories_per_unit: 70,
          protein_per_unit: 6,
          fat_per_unit: 5,
        },
        {
          name: "Abacate",
          quantity: 50,
          unit: "gramas",
          category: "Gordura boa",
          calories_per_unit: 160,
          fat_per_unit: 15,
        },
        {
          name: "Café sem açúcar",
          quantity: 1,
          unit: "xícara",
        },
      ],
      instructions:
        "Mexa os ovos em fogo baixo, sirva com abacate amassado. Acompanhe com café sem açúcar.",
      preparation_time: 10,
      cooking_time: 5,
      difficulty: "easy",
      is_consumed: false,
      active: true,
    },
    {
      id: "snack-1",
      name: "Lanche da Manhã",
      meal_type: "snack",
      time: "10:30",
      calories: 150,
      protein: 25,
      carbs: 5,
      fat: 2,
      image: require("../../../../../assets/images/protein-types.jpeg"),
      ingredients: [
        {
          name: "Whey Protein",
          quantity: 30,
          unit: "gramas",
          category: "Suplemento",
          calories_per_unit: 120,
          protein_per_unit: 25,
        },
        {
          name: "Água",
          quantity: 300,
          unit: "ml",
        },
      ],
      instructions:
        "Misture o whey protein com água gelada e bata bem até dissolver completamente.",
      difficulty: "easy",
      is_consumed: true,
      active: true,
    },
    {
      id: "lunch-1",
      name: "Almoço",
      meal_type: "lunch",
      time: "12:30",
      calories: 500,
      protein: 45,
      carbs: 40,
      fat: 15,
      image: require("../../../../../assets/images/hipertrofia-muscular.jpg"),
      ingredients: [
        {
          name: "Peito de Frango Grelhado",
          quantity: 200,
          unit: "gramas",
          category: "Proteína",
          calories_per_unit: 165,
          protein_per_unit: 31,
        },
        {
          name: "Arroz Integral",
          quantity: 80,
          unit: "gramas",
          category: "Carboidrato",
          calories_per_unit: 111,
          carbs_per_unit: 23,
        },
        {
          name: "Brócolis",
          quantity: 150,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 34,
          protein_per_unit: 3,
        },
        {
          name: "Salada Verde",
          quantity: 100,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 15,
        },
        {
          name: "Azeite",
          quantity: 1,
          unit: "colher de sopa",
          category: "Gordura",
          calories_per_unit: 120,
          fat_per_unit: 14,
        },
      ],
      instructions:
        "Tempere o frango com sal, pimenta e ervas. Grelhe por 6-8 minutos de cada lado. Refogue os brócolis no vapor. Sirva com arroz integral e salada temperada com azeite.",
      preparation_time: 15,
      cooking_time: 20,
      difficulty: "medium",
      is_consumed: false,
      active: true,
    },
    {
      id: "snack-2",
      name: "Lanche da Tarde",
      meal_type: "snack",
      time: "16:00",
      calories: 200,
      protein: 8,
      carbs: 15,
      fat: 12,
      image: require("../../../../../assets/images/Healthy-Fats.jpg"),
      ingredients: [
        {
          name: "Iogurte Natural",
          quantity: 150,
          unit: "gramas",
          category: "Laticínio",
          calories_per_unit: 59,
          protein_per_unit: 10,
        },
        {
          name: "Amêndoas",
          quantity: 20,
          unit: "gramas",
          category: "Oleaginosa",
          calories_per_unit: 579,
          fat_per_unit: 50,
        },
        {
          name: "Morango",
          quantity: 100,
          unit: "gramas",
          category: "Fruta",
          calories_per_unit: 32,
          carbs_per_unit: 8,
        },
      ],
      instructions:
        "Corte os morangos em pedaços pequenos. Misture com o iogurte natural e finalize com as amêndoas picadas.",
      difficulty: "easy",
      is_consumed: false,
      active: false,
    },
    {
      id: "dinner-1",
      name: "Jantar",
      meal_type: "dinner",
      time: "19:30",
      calories: 400,
      protein: 40,
      carbs: 20,
      fat: 18,
      image: require("../../../../../assets/images/lose-weight.webp"),
      ingredients: [
        {
          name: "Salmão Grelhado",
          quantity: 180,
          unit: "gramas",
          category: "Proteína",
          calories_per_unit: 208,
          protein_per_unit: 22,
          fat_per_unit: 12,
        },
        {
          name: "Batata Doce",
          quantity: 100,
          unit: "gramas",
          category: "Carboidrato",
          calories_per_unit: 86,
          carbs_per_unit: 20,
        },
        {
          name: "Espinafre Refogado",
          quantity: 150,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 23,
          protein_per_unit: 3,
        },
      ],
      instructions:
        "Tempere o salmão com limão, sal e pimenta. Asse no forno por 15min a 180°C. Cozinhe a batata doce no vapor. Refogue o espinafre com alho.",
      cooking_time: 15,
      difficulty: "medium",
      is_consumed: false,
      active: true,
    },
    {
      id: "breakfast-2",
      name: "Panqueca Proteica",
      description: "Panqueca rica em proteínas com banana",
      meal_type: "breakfast",
      time: "08:30",
      calories: 420,
      protein: 35,
      carbs: 25,
      fat: 18,
      image: require("../../../../../assets/images/protein-types.jpeg"),
      ingredients: [
        {
          name: "Ovos",
          quantity: 2,
          unit: "unidades",
          category: "Proteína",
          calories_per_unit: 70,
          protein_per_unit: 6,
        },
        {
          name: "Whey Protein",
          quantity: 30,
          unit: "gramas",
          category: "Suplemento",
          calories_per_unit: 120,
          protein_per_unit: 25,
        },
        {
          name: "Banana",
          quantity: 1,
          unit: "unidade",
          category: "Fruta",
          calories_per_unit: 89,
          carbs_per_unit: 23,
        },
      ],
      instructions:
        "Bata os ovos com whey protein. Amasse a banana e misture. Faça panquecas pequenas em frigideira antiaderente.",
      preparation_time: 5,
      cooking_time: 10,
      difficulty: "easy",
      is_consumed: false,
      active: false,
    },
    {
      id: "lunch-2",
      name: "Salada de Atum",
      description: "Salada fresca com atum e vegetais",
      meal_type: "lunch",
      time: "13:00",
      calories: 380,
      protein: 32,
      carbs: 15,
      fat: 22,
      image: require("../../../../../assets/images/lose-weight.webp"),
      ingredients: [
        {
          name: "Atum em Lata",
          quantity: 150,
          unit: "gramas",
          category: "Proteína",
          calories_per_unit: 116,
          protein_per_unit: 26,
        },
        {
          name: "Mix de Folhas",
          quantity: 100,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 20,
        },
        {
          name: "Tomate Cereja",
          quantity: 80,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 18,
        },
        {
          name: "Azeite Extra Virgem",
          quantity: 2,
          unit: "colheres de sopa",
          category: "Gordura",
          calories_per_unit: 120,
          fat_per_unit: 14,
        },
      ],
      instructions:
        "Misture todos os vegetais em uma tigela. Adicione o atum escorrido e tempere com azeite, sal e limão.",
      preparation_time: 10,
      difficulty: "easy",
      is_consumed: false,
      active: false,
    },
    {
      id: "dinner-2",
      name: "Omelete de Vegetais",
      description: "Omelete leve com vegetais variados",
      meal_type: "dinner",
      time: "20:00",
      calories: 320,
      protein: 28,
      carbs: 12,
      fat: 18,
      image: require("../../../../../assets/images/Healthy-Fats.jpg"),
      ingredients: [
        {
          name: "Ovos",
          quantity: 3,
          unit: "unidades",
          category: "Proteína",
          calories_per_unit: 70,
          protein_per_unit: 6,
        },
        {
          name: "Abobrinha",
          quantity: 100,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 17,
        },
        {
          name: "Pimentão",
          quantity: 50,
          unit: "gramas",
          category: "Vegetais",
          calories_per_unit: 20,
        },
        {
          name: "Queijo Cottage",
          quantity: 50,
          unit: "gramas",
          category: "Laticínio",
          calories_per_unit: 98,
          protein_per_unit: 11,
        },
      ],
      instructions:
        "Refogue os vegetais em pouco óleo. Bata os ovos e despeje na frigideira. Adicione o queijo cottage e dobre a omelete.",
      preparation_time: 8,
      cooking_time: 12,
      difficulty: "medium",
      is_consumed: false,
      active: false,
    },
  ],
});
